version: "3.8"
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    restart: always
  server:
    image: server
    build: server
    env_file:
      - ./server/.env
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${RDS_USERNAME}
      MYSQL_PASSWORD: ${RDS_PASSWORD}
      MYSQL_HOST: db
    ports:
      - "3001:3001"
    depends_on:
      - db
    restart: on-failure
